# Configuration pour PostgreSQL local (Base par défaut 'postgres' qui existe toujours)
# Si vous créez une base 'covoiturage_db', vous pourrez modifier l'URL ci-dessous.
spring.datasource.url=jdbc:postgresql://localhost:5432/covoiturage_db
spring.datasource.username=postgres
spring.datasource.password=0000

# Mettre à jour automatiquement les schémas dans la base de données (idéal pour le dév)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Clé secrète JWT en Base64 utilisée pour signer les tokens (exemple statique pour dev)
# Généré de manière aléatoire au format hexadécimal/base64 sécurisé pour la longueur requise.
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Port du serveur Backend
server.port=8080
